import { RecipeCardItem } from '@/recipes/models/Recipes';

export const dummyRecipes: RecipeCardItem[] = [
  {
    id: '1',
    title: 'Sweet Potato Puree',
    description:
      'Smooth and creamy sweet potato puree, perfect for first foods.',
    imageUrl:
      'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=400',
    rating: 4.8,
    reviewCount: 245,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 4,
    maxMonths: 6,
    isPremium: false,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Banana Oatmeal Pancakes',
    description:
      'Fluffy pancakes made with banana and oats, naturally sweetened.',
    imageUrl:
      'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
    rating: 4.9,
    reviewCount: 523,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 9,
    maxMonths: undefined,
    isPremium: true,
  },
  {
    id: '3',
    title: 'Avocado Toast Fingers',
    description:
      'Soft whole grain toast topped with mashed avocado for easy gripping.',
    imageUrl:
      'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
    rating: 4.7,
    reviewCount: 189,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 10,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '4',
    title: 'Chicken & Veggie Meatballs',
    description:
      'Tender meatballs packed with hidden vegetables and lean protein.',
    imageUrl:
      'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400',
    rating: 4.6,
    reviewCount: 312,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 12,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '5',
    title: 'Blueberry Chia Pudding',
    description:
      'Nutritious chia pudding with fresh blueberries and coconut milk.',
    imageUrl:
      'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    rating: 4.5,
    reviewCount: 156,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 8,
    maxMonths: undefined,
    isPremium: true,
  },
  {
    id: '6',
    title: 'Mac & Cheese Bites',
    description:
      'Creamy mac and cheese formed into easy-to-hold bite-sized portions.',
    imageUrl: 'https://images.unsplash.com/photo-1550460038-6d7fdbf1c29b?w=400',
    rating: 4.9,
    reviewCount: 678,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 11,
    maxMonths: undefined,
    isPremium: true,
    isFeatured: true,
  },
  {
    id: '7',
    title: 'Carrot & Ginger Puree',
    description: 'Warm and soothing carrot puree with a hint of ginger.',
    imageUrl:
      'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
    rating: 4.4,
    reviewCount: 98,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 5,
    maxMonths: 7,
    isPremium: false,
  },
  {
    id: '8',
    title: 'Mini Egg Muffins',
    description: 'Protein-packed egg muffins with cheese and veggies.',
    imageUrl:
      'https://images.unsplash.com/photo-1603046891726-36bfd957e0df?w=400',
    rating: 4.8,
    reviewCount: 421,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 10,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '9',
    title: 'Quinoa & Veggie Bowl',
    description: 'Colorful quinoa bowl with soft-cooked vegetables and herbs.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    rating: 4.6,
    reviewCount: 267,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 9,
    maxMonths: undefined,
    isPremium: true,
  },
  {
    id: '10',
    title: 'Apple Cinnamon Oatmeal',
    description:
      'Warm oatmeal with tender apple pieces and a sprinkle of cinnamon.',
    imageUrl:
      'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=400',
    rating: 4.7,
    reviewCount: 334,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 6,
    maxMonths: undefined,
    isPremium: false,
    isFeatured: true,
  },
  {
    id: '11',
    title: 'Turkey & Sweet Potato Hash',
    description: 'Savory ground turkey mixed with diced sweet potatoes.',
    imageUrl:
      'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
    rating: 4.5,
    reviewCount: 178,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 12,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '12',
    title: 'Yogurt & Berry Parfait',
    description: 'Creamy Greek yogurt layered with fresh berries and granola.',
    imageUrl:
      'https://images.unsplash.com/photo-1488477304112-4944851de03d?w=400',
    rating: 4.8,
    reviewCount: 445,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 8,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '13',
    title: 'Butternut Squash Soup',
    description: 'Silky smooth butternut squash soup with a touch of cream.',
    imageUrl:
      'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400',
    rating: 4.6,
    reviewCount: 201,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 6,
    maxMonths: 10,
    isPremium: false,
  },
  {
    id: '14',
    title: 'Mini Pizza Bites',
    description: 'Whole wheat mini pizzas with tomato sauce and melted cheese.',
    imageUrl:
      'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    rating: 4.9,
    reviewCount: 592,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 12,
    maxMonths: undefined,
    isPremium: true,
  },
  {
    id: '15',
    title: 'Pea & Mint Puree',
    description: 'Fresh pea puree with a hint of mint for a refreshing taste.',
    imageUrl:
      'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400',
    rating: 4.3,
    reviewCount: 87,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 5,
    maxMonths: 7,
    isPremium: false,
  },
  {
    id: '16',
    title: 'Salmon & Broccoli Bites',
    description: 'Omega-3 rich salmon mixed with finely chopped broccoli.',
    imageUrl:
      'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    rating: 4.7,
    reviewCount: 356,
    isVegan: false,
    isVegetarian: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 11,
    maxMonths: undefined,
    isPremium: false,
    isFeatured: true,
  },
  {
    id: '17',
    title: 'Mango Coconut Rice',
    description: 'Sweet coconut rice with fresh mango chunks.',
    imageUrl:
      'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    rating: 4.8,
    reviewCount: 289,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    minMonths: 8,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '18',
    title: 'Lentil Veggie Stew',
    description: 'Hearty lentil stew with colorful vegetables and herbs.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    rating: 4.5,
    reviewCount: 223,
    isVegan: true,
    isVegetarian: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    minMonths: 9,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '19',
    title: 'Cheese & Spinach Quesadilla',
    description:
      'Soft quesadilla filled with melted cheese and hidden spinach.',
    imageUrl:
      'https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=400',
    rating: 4.7,
    reviewCount: 467,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 12,
    maxMonths: undefined,
    isPremium: false,
  },
  {
    id: '20',
    title: 'Peach & Yogurt Smoothie Bowl',
    description:
      'Thick smoothie bowl with fresh peaches and topped with granola.',
    imageUrl:
      'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
    rating: 4.6,
    reviewCount: 312,
    isVegan: false,
    isVegetarian: true,
    isGlutenFree: false,
    isDairyFree: false,
    isNutFree: true,
    minMonths: 10,
    maxMonths: undefined,
    isPremium: false,
  },
];
